"""initial_schema

Revision ID: ed3691b2baad
Revises: 
Create Date: 2026-06-21 11:52:16.381089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed3691b2baad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_overrides',
    sa.Column('workout_date', sa.Date(), nullable=False),
    sa.Column('routine_tag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('workout_date')
    )
    op.create_table('exercise_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('body_part', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('instructions_en', sa.Text(), nullable=True),
    sa.Column('instructions_vi', sa.Text(), nullable=True),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('secondary_muscles', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('gif_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_pool_id'), 'exercise_pool', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_pool_name'), 'exercise_pool', ['name'], unique=False)
    op.create_index(op.f('ix_exercise_pool_pool_id'), 'exercise_pool', ['pool_id'], unique=True)
    op.create_table('weekly_presets',
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('routine_tag', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('day_of_week')
    )
    op.create_table('exercise_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('name_eng', sa.String(length=255), nullable=False),
    sa.Column('name_vie', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('instructions_en', sa.Text(), nullable=True),
    sa.Column('instructions_vi', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('pro_tips', sa.Text(), nullable=True),
    sa.Column('pro_tips_en', sa.Text(), nullable=True),
    sa.Column('pro_tips_vi', sa.Text(), nullable=True),
    sa.Column('tracking_type', sa.String(length=50), nullable=False),
    sa.Column('primary_muscle', sa.String(length=100), nullable=True),
    sa.Column('secondary_muscle', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['exercise_pool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_eng')
    )
    op.create_table('daily_workout_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('tracking_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_aggregated_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_master.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['log_id'], ['daily_workout_log.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'exercise_id', 'metric_type', name='unique_daily_exercise_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_aggregated_stats')
    op.drop_table('daily_workout_log')
    op.drop_table('exercise_master')
    op.drop_table('weekly_presets')
    op.drop_index(op.f('ix_exercise_pool_pool_id'), table_name='exercise_pool')
    op.drop_index(op.f('ix_exercise_pool_name'), table_name='exercise_pool')
    op.drop_index(op.f('ix_exercise_pool_id'), table_name='exercise_pool')
    op.drop_table('exercise_pool')
    op.drop_table('daily_overrides')
    # ### end Alembic commands ###
